site_name: My Mkdocs site
site_url: https://alexros177.github.io/mkdocs_1/
theme:
  name: material

site_author: Alex Ros
copyright: Alex Ros, My Mkdocs site, 2025  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  